encounts <- read_delim("~/w266final/counts.en", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
ptcounts <- read_delim("~/w266final/counts.pt", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
hist(ptcounts$X2)
ensorted <- sort(encounts$X2, decreasing = TRUE)
hist(ensorted[ensorted <= 5], col="blue", ylim = range(0,40000), xlab="Num",main="English Rare Words Tokenizer 1")
ptsorted <- sort(ptcounts$X2, decreasing = TRUE)
hist(ptsorted[ptsorted <= 5], col="blue", ylim = range(0,40000), xlab="Num",main="Portuguese Rare Words Tokenizer 1")

encounts2 <- read_delim("~/w266final/counts2.en", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
ptcounts2 <- read_delim("~/w266final/counts2.pt", "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
ensorted2 <- sort(encounts2$X2, decreasing = TRUE)
hist(ensorted2[ensorted2 <= 5], col="blue", ylim = range(0,40000), xlab="Num", main="English Rare Words Tokenizer 2")
ptsorted2 <- sort(ptcounts2$X2, decreasing = TRUE)
hist(ptsorted2[ptsorted2 <= 5], col="blue", ylim = range(0,40000), xlab="Num", main="Portuguese Rare Words Tokenizer 2")

vocabSizes = c(10000,20000,30000,40000,50000,60000,70000,80000,90000,100000)
y1 = lapply(vocabSizes, function(size) {sum(ensorted[size:length(ensorted)])/sum(ensorted)})
y2 = lapply(vocabSizes, function(size) {sum(ensorted2[size:length(ensorted2)])/sum(ensorted2)})
y3 = lapply(vocabSizes, function(size) {sum(ptsorted[size:length(ptsorted)])/sum(ptsorted)})
y4 = lapply(vocabSizes, function(size) {sum(ptsorted2[size:length(ptsorted2)])/sum(ptsorted2)})
print(unlist(y1))
print(y2)
print(y3)
print(y4)

lineEn <- read_csv("~/w266final/linelen.en", col_names = FALSE)
linePt <- read_csv("~/w266final/linelen.pt", col_names = FALSE)
barplot(linePt$X2[linePt$X1<=70])
barplot(lineEn$X2[lineEn$X1<=40])
bucket1 <- sum(lineEn$X2[0 < lineEn$X1 & lineEn$X1 <=5])
getProportion <- function(counts, min, max) {
  sum(counts$X2[min < counts$X1 & counts$X1 <= max])/sum(counts$X2)
}
getProportion(lineEn, 40, 50)
getProportion(lineEn, 40, 50)
getProportion(lineEn, 40, 50)
getProportion(lineEn, 40, 50)
getProportion(linePt, 40, 50)
getProportion(linePt, 0, 10)
getProportion(linePt, 40, 50)
getProportion(linePt, 40, 50)
